# Numpy

In [ ]:
import numpy as np
from numpy import *

A estrutura de dados base do *numpy* sao os **arrays**

In [3]:
import numpy as np

# criando um array unidimensional a partir de uma lista
lst = [1,3,5,7,9,10]
a1d = np.array(lst)
print(a1d)

print(lst)

[ 1  3  5  7  9 10]
[1, 3, 5, 7, 9, 10]


In [10]:
b1d = np.zeros((8))
print('ald=', b1d)

b1d = np.ones((8))
print('bld=', b1d)

b1d = np.arange((8))
print('cld=', b1d)

b1d = np.linspace(1,2,5)
print('dld=', b1d)


bld= [0. 0. 0. 0. 0. 0. 0. 0.]
bld= [1. 1. 1. 1. 1. 1. 1. 1.]
bld= [0 1 2 3 4 5 6 7]
bld= [1.   1.25 1.5  1.75 2.  ]


## Criando arrays bidimensionais a partir de uma lista de listas

In [7]:
a2d = np.array([[1,3,5,7,9],
                [2,4,6,10,12],
                [0,1,2,3,4]])

a2d

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6, 10, 12],
       [ 0,  1,  2,  3,  4]])

In [6]:
import numpy as np

b2d = np.zeros((5,10))
print(b2d)

c2d = np.identity(4)
print(c2d)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Numpy arrays sao objetos chamados _ndarrays_ e possuem diversos **atributos**:

- _ndarray.ndim_ - numero de eixos (dimensoes do array)
- _ndarray.shape_ - uma tupla de inteiros indicando o tamanho do array em cada dimensao
- _ndarray.size_ - o numero total de elementos no array
- _ndarray.dtype_ - tipo dos elementos no array
- _ndarray.itemsize_ 0 o tamanho em bytes de cada elemento do array
- _ndarray.data_ - o buffer de memoria contendo os elementos do array

In [8]:
a = np.zeros((5))
b = np.zeros((5,1))
print('a.shape', a.shape)
print('b.shape', b.shape)
print('a.ndim', a.ndim)
print('b.ndim', b.ndim)

a.shape (5,)
b.shape (5, 1)
a.ndim 1
b.shape 2


## Percorrendo elementos com um *loop*
A iteracao eh feita por linhas , se o que se busca sao os elementos, deve-se utilizar um laco duplo ou entao a versao 'flat' do array

In [ ]:
# percorrendo as linhas
for i,row in enumerate(a2d):
    print('linha ',i, ' = ', row)

print(5*'--', 'iterando o array')
#perorrendo elementos
for i,r in enumerate(a2d):
    for j,e in enumerate(r):
        print('elemento ', i , ' ', j, ' = ', e)

print(5*'--', 'utilizando indices')
#pode-se tamem utilizar indices diretamente
for i in range(a2d.shape[0]):
    for j in range(a2d.shape[1]):
        print('elemento ',i, ' ', j, ' = ', a2d[i,j])

print(5*'--', 'utilizando flat')

## Slicing arrays
A melhor forma de se percorrer um array eh por meio de _slicing_ , evitando uso de loops for, que sao computacionalmente muito pesados.

- Array slicing funciona como em listas, mas em multiplas dimensoes
- Omitir um indice corresponde a recuperar toda a dimensao omitida
- Um slice eh uma visao (*VIEW*) do array original (similar a uma referencia), isto eh, o dado nao eh copiado