# **SME0142 - Álgebra Linear e Aplicações**
Docente: Cynthia de Oliveira Lage Ferreira

PAE - Luiz Otávio Toratti
# **Avaliação 2**
16 de dezembro de 2021

# Aluno:

# Orientações Gerais

*   Esta avaliação é **individual** e deverá ser desenvolvida na plataforma Colab (https://colab.research.google.com/).

*   Cada aluno deverá produzir um arquivo .ipynb contendo tanto os exercícios teóricos quanto os práticos. Os alunos que desejarem, poderão enviar, também, um arquivo .pdf com as soluções teóricas. Sejam organizados !

*   Os arquivos deverão estar identificados por **NOMEDOALUNO-NoUSP-TURMA.ipynb** e **NOMEDOALUNO-NoUSP-TURMA.pdf** (e compactados em uma pasta única NOMEDOALUNO-NoUSP-TURMA) a fim de facilitar a organização das atividades pela professora.

*  Os arquivos deverão ser enviados **até às 20h do dia 18/12** através da plataforma e-disciplinas da USP (https://edisciplinas.usp.br/). **Os arquivos recebidos por e-mail não serão corrigidos.** Arquivos enviados fora do prazo também não serão corrigidos!

*   Apenas os alunos que estiverem com a **situação regularizada no Sistema Jupiter** terão suas avaliações corrigidas.

* Todos os exercícios deverão conter **justificativas** teóricas. Faça um **pequeno resumo da teoria abordada em cada exercício**. Todos os códigos utilizados para resolver os problemas deverão ser apresentados, executados e minimamente comentados. **Questões com respostas sem justificativas não serão consideradas.**

**BOA PROVA!**

In [ ]:
#Bibliotecas Utilizadas
import numpy as np
import matplotlib.pyplot as plt

# Exercício 1

Use o Teorema Espectral e encontre uma trasformação linear cujos autovetores são  $v_1=[1,1]$  e  $v_2=[1,−1]$  e os autovalores correspondentes são  $\alpha_1$ e  $\alpha_2$ , respectivamente. Verifique graficamente o efeito desta transformação no círculo  $x_2+y_2=1$, quando: 

a) $\alpha_1 = 0.5$ e $\alpha_2 = 0.1$.

b) $\alpha_1 = 0.1$ e $\alpha_2 = 0.5$.

c) $\alpha_1 = 0.5$ e $\alpha_2 = 0.5$.

Comente os resultdos obtidos.

In [ ]:
# Montando a transformação linear (uma para cada ítem)



A1 = 
A2 = 
A3 = 

# Gerando pontos no ciruclo
n = 100 # numero de pontos sobre o circulo
t = np.linspace(0,2*np.pi,n)
X = np.zeros((2,n))
X[0,:] = np.cos(t)
X[1,:] = np.sin(t)

# Encontrando a transformacao de X
A1X =
A2X = 
A3X = 

# Plotando os gráficos
fig, (ax1,ax2, ax3, ax4) = plt.subplots(nrows=1,ncols=4)

ax1.set_aspect('equal')
ax1.plot(X[0,:],X[1,:])

ax2.set_aspect('equal')
ax2.plot(A1X[0,:],A1X[1,:])

ax3.set_aspect('equal')
ax3.plot(A2X[0,:],A2X[1,:])

ax4.set_aspect('equal')
ax4.plot(A3X[0,:],A3X[1,:])

# Exercício 2

a) Dada uma base qualquer de um subespaço vetorial do $R^{n}$, escreva um código para encontrar uma base ortonormal para este subespaço. Teste o seu código para a base dada pelas colunas da matriz  **V**  gerada no código abaixo. 

b) Faça um teste para verificar que a base obtida é de fato ortonormal.



In [ ]:
#V = np.random.randint(0,20,size=(20,10))
#print(V)


[[19  2 17  5  9 17  9 15  8  7]
 [12  8 13  1  5 12 16 16  8  3]
 [16  6  4 13  5  6  5  7  7  4]
 [ 9  0  2 12  8  5 13  0 17 18]
 [17  9 12  4  7  8  0  6  3 15]
 [ 1 17  0  6 10  4 17 18 19  7]
 [ 2  5 17  2 13 17 11  0 10 17]
 [16  2  9  3 16 10 19  1  6 13]
 [16 15 11 15 11  7 14 12  7  2]
 [ 9  3  7  5 13  4 16 17 16  3]
 [ 7 14  3  4  7  5  1 12 16 10]
 [ 8 11 14 14  5  1  9 13  9 15]
 [ 4  8 11 10  2 12 17  3 16  4]
 [ 2 16 16  6 18 13 11  9  9 13]
 [10 15 12  3  3  7 11  8 11  3]
 [ 6  5 11 19  8  2 18 19 13 11]
 [18 16 17  5  9 15  9 19 15  5]
 [11 10  1  7 11  1  6  5  7  2]
 [13 12  4 18 13 14 11 14 11  5]
 [18 14  3 16 14  8  4  1  9 11]]


In [ ]:
# a) Ortonormalização de uma base qualquer dada e teste do código em V




# b) Teste que verifica se a base obtida é de fato ortonormal





# Exercício 3

Considere o conjunto de dados *sklearn.datasets load_wine*. 

Uma operação muito importante antes de aplicar PCA é "padronizar" os dados, fazendo com que estes tenham média zero e variânica um. Utilize apenas as duas componentes de maior variância e projete os dados originais nestas duas componentes. Faça dois "scatter plots", considerando:

a) os dados não padronizados.

b) os dados padronizados.

O que você pode observar ?

**DICA:** Utilize o método *StandardScaler* disponível no pacote *sklearn.preprocessing* para realizar a padronização.

c) Considerando agora 3 componentes principais e os dados padronizados, projete os dados nestas 3 componentes e calcule a porcentagem da variância explicada. O que ela significa ?


In [1]:
from sklearn.datasets import load_wine
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA # Será permitido usar a função pronta para o PCA

In [2]:
# lendo a base de dados
wine = load_wine()
wine_data = wine.data
wine_data.shape

(178, 13)

In [4]:
# atributos dos dados
wine_dataset = pd.DataFrame(final_wine_data)
features =wine.feature_names
features

NameError: ignored

In [3]:
# 3 diferentes classes
print(wine.target)
labels = np.reshape(wine.target,(178,1))
final_wine_data = np.concatenate([wine_data,labels],axis=1)


features_labels = np.append(features,'label')
wine_dataset.columns = features_labels
wine_dataset['label'].replace(0, 'Classe 1',inplace=True)
wine_dataset['label'].replace(1, 'Classe 2',inplace=True)
wine_dataset['label'].replace(2, 'Classe 3',inplace=True)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


NameError: ignored

In [ ]:
# Dados
x1 = wine_dataset.loc[:, features].values
print(x1.shape)

(178, 13)


# Exercício 4

O crescimento populacional do Brasil ao longo dos anos pode ser observado na tabela abaixo, de acordo com dados do Censo-IBGE: 


Ano | População (milhões)
--- | :---: 
1872 | 9,9
1890 | 14,3
1900 | 17,4
1920 | 30,6
1940 | 41,2
1950 | 51,9
1960 | 70,9
1970 | 94,5
1980 | 121,1
1991 | 146,9
2000 | 169,5
2010 | 190,7


Tabela: *População do Brasil, em milhões de pessoas, entre os anos de 1872-2010. Dados Censo-IBGE.*



O último Censo foi realizado em 2010 e, devido à pandemia da Covid-19, o de 2020 foi adiado. Por isso, não é possível saber, com maior precisão, a população atual do país. Com o objetivo de estimar a população do Brasil em 2021, ajuste, no sentido dos mínimos quadrados, uma reta e uma parábola aos dados representados na tabela.

a) Qual das duas aproximações você considera melhor para estimar a população atual do país ? Justifique a sua resposta calculando o erro da aproximação. Mostre, também, os gráficos das duas aproximações obtidas.

b) Qual seria a população estimada do Brasil em 2021 ? Justifique.

In [ ]:
# Dados
x = [1872, 1890, 1900, 1920, 1940, 1950, 1960, 1970, 1980, 1991, 2000, 2010] 
y = [9.9, 14.3, 17.4, 30.6, 41.2, 51.9, 70.9, 94.5, 121.1, 146.9, 169.5, 190.7]

