# Numpy

In [1]:
import numpy as np
from numpy import *

A estrutura de dados base do *numpy* sao os **arrays**

In [2]:
import numpy as np

# criando um array unidimensional a partir de uma lista
lst = [1,3,5,7,9,10]
a1d = np.array(lst)
print(a1d)

print(lst)

[ 1  3  5  7  9 10]
[1, 3, 5, 7, 9, 10]


In [3]:
b1d = np.zeros((8))
print('ald=', b1d)

b1d = np.ones((8))
print('bld=', b1d)

b1d = np.arange((8))
print('cld=', b1d)

b1d = np.linspace(1,2,5)
print('dld=', b1d)


ald= [0. 0. 0. 0. 0. 0. 0. 0.]
bld= [1. 1. 1. 1. 1. 1. 1. 1.]
cld= [0 1 2 3 4 5 6 7]
dld= [1.   1.25 1.5  1.75 2.  ]


## Criando arrays bidimensionais a partir de uma lista de listas

In [4]:
a2d = np.array([[1,3,5,7,9],
                [2,4,6,10,12],
                [0,1,2,3,4]])

a2d

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6, 10, 12],
       [ 0,  1,  2,  3,  4]])

In [5]:
import numpy as np

b2d = np.zeros((5,10))
print(b2d)

c2d = np.identity(4)
print(c2d)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Numpy arrays sao objetos chamados _ndarrays_ e possuem diversos **atributos**:

- _ndarray.ndim_ - numero de eixos (dimensoes do array)
- _ndarray.shape_ - uma tupla de inteiros indicando o tamanho do array em cada dimensao
- _ndarray.size_ - o numero total de elementos no array
- _ndarray.dtype_ - tipo dos elementos no array
- _ndarray.itemsize_ 0 o tamanho em bytes de cada elemento do array
- _ndarray.data_ - o buffer de memoria contendo os elementos do array

In [6]:
a = np.zeros((5))
b = np.zeros((5,1))
print('a.shape', a.shape)
print('b.shape', b.shape)
print('a.ndim', a.ndim)
print('b.ndim', b.ndim)

a.shape (5,)
b.shape (5, 1)
a.ndim 1
b.ndim 2


## Percorrendo elementos com um *loop*
A iteracao eh feita por linhas , se o que se busca sao os elementos, deve-se utilizar um laco duplo ou entao a versao 'flat' do array

In [7]:
# percorrendo as linhas
for i,row in enumerate(a2d):
    print('linha ',i, ' = ', row)

print(5*'--', 'iterando o array')
#perorrendo elementos
for i,r in enumerate(a2d):
    for j,e in enumerate(r):
        print('elemento ', i , ' ', j, ' = ', e)

print(5*'--', 'utilizando indices')
#pode-se tamem utilizar indices diretamente
for i in range(a2d.shape[0]):
    for j in range(a2d.shape[1]):
        print('elemento ',i, ' ', j, ' = ', a2d[i,j])

print(5*'--', 'utilizando flat')

linha  0  =  [1 3 5 7 9]
linha  1  =  [ 2  4  6 10 12]
linha  2  =  [0 1 2 3 4]
---------- iterando o array
elemento  0   0  =  1
elemento  0   1  =  3
elemento  0   2  =  5
elemento  0   3  =  7
elemento  0   4  =  9
elemento  1   0  =  2
elemento  1   1  =  4
elemento  1   2  =  6
elemento  1   3  =  10
elemento  1   4  =  12
elemento  2   0  =  0
elemento  2   1  =  1
elemento  2   2  =  2
elemento  2   3  =  3
elemento  2   4  =  4
---------- utilizando indices
elemento  0   0  =  1
elemento  0   1  =  3
elemento  0   2  =  5
elemento  0   3  =  7
elemento  0   4  =  9
elemento  1   0  =  2
elemento  1   1  =  4
elemento  1   2  =  6
elemento  1   3  =  10
elemento  1   4  =  12
elemento  2   0  =  0
elemento  2   1  =  1
elemento  2   2  =  2
elemento  2   3  =  3
elemento  2   4  =  4
---------- utilizando flat


## Slicing arrays
A melhor forma de se percorrer um array eh por meio de _slicing_ , evitando uso de loops for, que sao computacionalmente muito pesados.

- Array slicing funciona como em listas, mas em multiplas dimensoes
- Omitir um indice corresponde a recuperar toda a dimensao omitida
- Um slice eh uma visao (*VIEW*) do array original (similar a uma referencia), isto eh, o dado nao eh copiado

In [8]:
a2d = np.array([[1,3,5,7,9],
                [2,4,6,10,12],
                [0,1,2,3,4]])


# slicing the lines
print('a2d[1, :] - Recupera a linha de indice 1 (equivalent to a2d[1])\n', a2d[1, :])

# slicing the columns
print('a2d[:, 2] - Recupera a coluna de indice 2\n', a2d[:, 2])

# slicing the blocks
print('a2d[1:, 2:5] - Recupera o bloco a partir da linha de indice 1 e  colunas 2,3 e 4\n', a2d[1:, 2:5])


a2d[1, :] - Recupera a linha de indice 1 (equivalent to a2d[1])
 [ 2  4  6 10 12]
a2d[:, 2] - Recupera a coluna de indice 2
 [5 6 2]
a2d[1:, 2:5] - Recupera o bloco a partir da linha de indice 1 e  colunas 2,3 e 4
 [[ 6 10 12]
 [ 2  3  4]]


## Metodos flatten, ravel e reshape

- O metodo reshape permite reformatar o array mofidicando o numero de linhas e colunas, porem, a nova 'shape' deve possuir o mesmo numero de elementos do array original

- O metodo ravel concatena as linhas da matriz em um array unidimensional

- O Metodo flatten tambem concatena as linhas da matriz em um array unidimensional, porem, faz uma copia dos elementos. O Metodo ravel gera uma **view**, portanto se algum elemento for modificado, o array original tambem o eh


In [11]:
# criando um array randomico unidimensional e dps tranformando ele em uma matriz 3x3
a = np.arange(9).reshape((3,3))
print('a:\n', a)

# concatenando as linhas da matriz em um vetor
b = a.ravel()
print('b: \n', b)



a:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
b: 
 [0 1 2 3 4 5 6 7 8]


In [15]:
x = np.arange(18).reshape(3,6)

# calculando uma mascara booleana onde o valor True
# corresponde aos elementos maiores que 7
mask = (x > 7)

# mascara booleana da matriz para a condicao dada
print(mask)

# recuperando apenas os valores que sao aprovados pela mascara
print(x[mask])

# Zerando apenas os elementos que passaram na mascara
x[mask] = 0
print(x)



[[False False False False False False]
 [False False  True  True  True  True]
 [ True  True  True  True  True  True]]
[ 8  9 10 11 12 13 14 15 16 17]
[[0 1 2 3 4 5]
 [6 7 0 0 0 0]
 [0 0 0 0 0 0]]


## Regarding 'Views'

- Uma **view** eh criada ao fatiar (sliccing) o array
- Uma **view** eh uma referencia a uma parte de um array
- Alterar elementos da **view** afeta o array original
- Se necessario, voce pode explicitamente fazer uma copia  utilizando o metodo **copy**


## I/O with Numpy
Numpy fornece metodos para ler e escrever arrays em arquivos. A sintaxe basica para leitura de arrays a partir de um arquivo eh

In [ ]:
nome_array = np.loadtxt('nome_do_arquivo')

---

# Broadcasting